INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (2, 'Grupo de Karatê Shotokan');
INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (5, 'Equipe Kung Fu Garra de Águia');
INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (15, 'Grupo de Estudos Tai Chi Chuan');
INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (8, 'Projeto Capoeira Angola');
