INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (10, 'Grupo de Karatê Shotokan');
INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (4, 'Equipe Kung Fu Garra de Águia');
INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (13, 'Grupo de Estudos Tai Chi Chuan');
INSERT INTO ATIVIDADE_GRUPO_EXTENSAO (ID_ATIVIDADE, NOME_GRUPO) VALUES (12, 'Projeto Capoeira Angola');
